AS=ca65
LD=ld65

BUILD=build
SRC=src
INC=inc
CFG=cfg
GENHEADER=tools/genheader.sh

CONFIG=$(CFG)/nrom128.cfg
PRG=$(BUILD)/prg.bin
CHR=$(BUILD)/chr.bin
NES=$(BUILD)/main.nes

all: $(NES)

# Prepend the iNES header
$(NES): $(PRG) $(CHR)
	printf '\x4e\x45\x53\x1a' > $@
	printf '\x01' >> $@
	printf '\x01' >> $@
	printf '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' >> $@
	cat $(PRG) >> $@
	cat $(CHR) >> $@

# Build the PRG ROM
$(PRG): $(BUILD)/main.o $(BUILD)/pad.o | $(BUILD) $(CONFIG)
	$(LD) -C $(CONFIG) -o $@ $^

# Generate the raw CHR ROM
# NOTE: This would most likely be generated by a graphics tool.
build/chr.bin:
	printf '\xff\xff\xff\xff\xff\xff\xff\xff' > $@
	printf '\x00\x00\x00\x00\x00\x00\x00\x00' >> $@
	dd if=/dev/zero bs=8176 count=1 >> $@ 2> /dev/null

# Compile the main program
$(BUILD)/main.o: $(SRC)/main.s $(INC)/ppu.inc $(INC)/apu.inc $(INC)/boot.inc | $(BUILD)
	$(AS) -t none -I inc -o $@ $<

$(BUILD)/pad.o: $(SRC)/pad.s | $(BUILD)
	$(AS) -t none -I inc -o $@ $<

$(BUILD):
	mkdir -p $(BUILD)

clean:
	rm -rf $(BUILD)
